FROM alpine:latest

RUN apk add --no-cache \
    bash \
    curl \
    git \
    nodejs \
    npm \
    go \
    vips-dev \
    libc6-compat \
    build-base \
    ca-certificates

RUN curl -L https://github.com/gohugoio/hugo/releases/download/v0.145.0/hugo_extended_0.145.0_Linux-64bit.tar.gz \
    | tar -xz -C /usr/local/bin hugo

WORKDIR /src
ENTRYPOINT ["sh"]
CMD ["-C", "hugo && tail -f /dev/null"]
