FROM debian:bullseye-slim


RUN apt-get update && apt-get install -y \
    bash \
    curl \
    wget \
    git \
    nano \
    gnupg \
    ca-certificates \
    unzip \
    build-essential && \
    curl -fsSL https://deb.nodesource.com/setup_18.x | bash - && \
    apt-get install -y nodejs golang && \
    apt-get clean && rm -rf /var/lib/apt/lists/*


RUN curl -L -o /tmp/dart-sass.tar.gz https://github.com/sass/dart-sass/releases/download/1.86.0/dart-sass-1.86.0-linux-x64.tar.gz && \
    mkdir -p /opt/dart-sass && \
    tar -xzf /tmp/dart-sass.tar.gz -C /opt/dart-sass --strip-components=1 && \
    ln -s /opt/dart-sass/sass /usr/local/bin/sass && \
    rm /tmp/dart-sass.tar.gz



RUN curl -L https://github.com/gohugoio/hugo/releases/download/v0.145.0/hugo_extended_0.145.0_Linux-64bit.tar.gz \
    | tar -xz -C /usr/local/bin hugo


WORKDIR /src
COPY package.json package-lock.json ./

RUN npm ci

RUN npm install -g @hbstack/node-packages

WORKDIR /src
ENTRYPOINT ["bash", "-c"]
CMD ["hugo --gc --minify && tail -f /dev/null"]
